### ISSUE TITLE
[Server Step 1.4] - prettier script does not work on windows

### ISSUE THREAD

**Issue by sfabriece** [Urigo/WhatsApp-Clone-Tutorial#3]
change the script from `"format": "prettier '**/*.ts' --write"` to `"format": "prettier \"**/*.ts\" --write"`

notice the escaped quotes.

**Comment by sfabriece** [comment]
How can I contribute the change if approved @Urigo?

**Comment by Urigo** [comment]
Thank you so much @sfabriece !
I've applied your changes to master.

Because Tortilla is currently rewriting the git history, as of today there are only 2 ways of applying your changes:
1. We would manually add them and then push the new history
2. You will learn Tortilla.

The issue with the first one is that then you won't get to see your commit in Github's history.
So for now I've added your name [here](https://github.com/urigo/whatsApp-Clone-Server#external-contributors) to give you the credit you deserve.

and maybe in the future you can learn Tortilla (I also hope we will make it easier to use and also maybe figure out a way to change that git history to accommodate multiple contributions for the same commit, I would love to hear ideas!)

Thank you for your contribution and I hope to get more!
